import React from "react";
import { getIsInterstate } from "../templateUtils.jsx";

export function OfficialYellowEWay({ invoice, printSet, gstSet }) {
  const { customer, lines = [], totals = {}, meta = {}, transportDetails = {}, shippingDetails = {} } = invoice;

  const sellerGstin = gstSet?.gstin || invoice.sellerDetails?.gstin || printSet?.gstin || "-";
  const sellerName = printSet?.companyName || invoice.sellerDetails?.companyName || "My Company";
  const sellerState = printSet?.state || invoice.sellerDetails?.state || meta?.placeOfSupply || meta?.billedToState || "Delhi";
  const dispatchFrom = shippingDetails?.dispatchFromAddress || shippingDetails?.placeOfDispatch || printSet?.address || invoice.sellerDetails?.address || "-";

  const customerGstin = meta?.billedToGstin || shippingDetails?.shippingGstin || shippingDetails?.shipToGSTIN || "-";
  const customerName = meta?.billingName || customer || "Walk-in Customer";
  const customerState = meta?.billedToState || shippingDetails?.state || meta?.placeOfSupply || "Delhi";
  const shipToAddress = shippingDetails?.shipToAddress || shippingDetails?.placeOfDelivery || meta?.billedToAddress || "-";

  const isInterstate = getIsInterstate(invoice, printSet, gstSet);

  let totalTaxable = 0;
  let totalCgst = 0;
  let totalSgst = 0;
  let totalIgst = 0;
  let totalCess = 0;

  lines.forEach((l) => {
    const q = Number(l.qty) || 0;
    const r = Number(l.rate || l.price) || 0;
    const d = Number(l.discount) || 0;
    const g = Number(l.gst) || 0;
    const rateAfterDisc = r * (1 - d / 100);
    const taxable = q * rateAfterDisc;
    const taxAmt = taxable * (g / 100);

    totalTaxable += taxable;

    if (isInterstate) {
      totalIgst += taxAmt;
    } else {
      totalCgst += taxAmt / 2;
      totalSgst += taxAmt / 2;
    }
    totalCess += (taxable * (Number(l.cess) || 0)) / 100;
  });

  const totalInvAmt = totalTaxable + totalCgst + totalSgst + totalIgst + totalCess;
  const ewbNo = transportDetails.ewbNumber || meta?.invoiceNumber || "-";

  const yellowHeaderBg = "#e3ec9c"; // Exact light lime/yellow tint from screenshot

  return (
    <div className="w-full bg-white p-4 font-sans text-[9.5px] leading-snug text-slate-900 space-y-2 border border-slate-300 shadow-sm">
      {/* Document Header */}
      <div className="border border-slate-400 p-3 mb-2 rounded-sm">
        <h1 className="text-xl font-bold text-slate-900 tracking-tight">e-Way Bill</h1>
      </div>

      {/* 1. E-WAY BILL Details */}
      <div className="border border-slate-400 rounded-sm overflow-hidden">
        <div className="py-1 px-2 font-bold text-slate-900 border-b border-slate-400" style={{ backgroundColor: yellowHeaderBg }}>
          1. E-WAY BILL Details
        </div>
        <table className="w-full text-left border-collapse border-slate-400">
          <tbody>
            <tr className="border-b border-slate-300">
              <td className="p-1.5 border-r border-slate-300 w-1/3">
                <span className="text-slate-600">eWay Bill No:</span> <span className="font-semibold">{ewbNo}</span>
              </td>
              <td className="p-1.5 border-r border-slate-300 w-1/3">
                <span className="text-slate-600">Generated Date:</span> <span className="font-semibold">{meta?.date || new Date().toLocaleDateString('en-IN')}</span>
              </td>
              <td className="p-1.5 w-1/3">
                <span className="text-slate-600">Generated By:</span> <span className="font-semibold">{sellerGstin !== "-" ? sellerGstin : sellerName}</span>
                <br />
                <span className="text-slate-600">Valid Upto:</span> <span className="font-semibold">{meta?.dueDate || "-"}</span>
              </td>
            </tr>
            <tr className="border-b border-slate-300">
              <td className="p-1.5 border-r border-slate-300">
                <span className="text-slate-600">Mode:</span> <span className="font-semibold">{transportDetails.modeOfTransport || "Road"}</span>
              </td>
              <td className="p-1.5 border-r border-slate-300">
                <span className="text-slate-600">Approx Distance:</span> <span className="font-semibold">{transportDetails.approxDistance ? `${transportDetails.approxDistance} km` : "-"}</span>
              </td>
              <td className="p-1.5" rowSpan={2}>
                <span className="text-slate-600">Transaction type:</span> <span className="font-semibold">Regular</span>
              </td>
            </tr>
            <tr>
              <td className="p-1.5 border-r border-slate-300">
                <span className="text-slate-600">Type:</span> <span className="font-semibold">Outward-Supply</span>
              </td>
              <td className="p-1.5 border-r border-slate-300">
                <span className="text-slate-600">Document Details:</span> <span className="font-semibold">Tax Invoice - {meta?.invoiceNumber || "-"} - {meta?.date || "-"}</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* 2. Address Details */}
      <div className="border border-slate-400 rounded-sm overflow-hidden">
        <div className="py-1 px-2 font-bold text-slate-900 border-b border-slate-400" style={{ backgroundColor: yellowHeaderBg }}>
          2. Address Details
        </div>
        <div className="grid grid-cols-2 divide-x divide-slate-400">
          {/* From */}
          <div className="p-2 space-y-1">
            <div className="font-bold py-0.5 px-1 rounded text-[9px]" style={{ backgroundColor: yellowHeaderBg }}>
              From
            </div>
            <p><span className="font-semibold">GSTIN:</span> {sellerGstin}</p>
            <p className="font-bold text-slate-900">{sellerName}</p>
            <p><span className="font-semibold">State:</span> {sellerState}</p>
            <p className="text-slate-600 mt-2">
              <span className="font-semibold text-slate-800">::Dispatch From::</span> {dispatchFrom}
            </p>
          </div>

          {/* To */}
          <div className="p-2 space-y-1">
            <div className="font-bold py-0.5 px-1 rounded text-[9px]" style={{ backgroundColor: yellowHeaderBg }}>
              To
            </div>
            <p><span className="font-semibold">GSTIN:</span> {customerGstin}</p>
            <p className="font-bold text-slate-900">{customerName}</p>
            <p><span className="font-semibold">State:</span> {customerState}</p>
            <p className="text-slate-600 mt-2">
              <span className="font-semibold text-slate-800">::Ship To::</span> {shipToAddress}
            </p>
          </div>
        </div>
      </div>

      {/* 3. Goods Details */}
      <div className="border border-slate-400 rounded-sm overflow-hidden space-y-0">
        <div className="py-1 px-2 font-bold text-slate-900 border-b border-slate-400" style={{ backgroundColor: yellowHeaderBg }}>
          3. Goods Details
        </div>

        {/* Table 1: Items list */}
        <table className="w-full text-left border-collapse table-fixed">
          <thead>
            <tr className="font-bold text-slate-900 border-b border-slate-400 text-center" style={{ backgroundColor: yellowHeaderBg }}>
              <th className="p-1.5 border-r border-slate-400 w-[15%]">HSN Code</th>
              <th className="p-1.5 border-r border-slate-400 w-[45%] text-left">Product Name & Desc</th>
              <th className="p-1.5 border-r border-slate-400 w-[12%]">Quantity</th>
              <th className="p-1.5 border-r border-slate-400 w-[14%]">Taxable Amount Rs.</th>
              <th className="p-1.5 w-[14%]">Tax Rate (C+S+I+Cess+Cess Non.Advol)</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-300">
            {lines.map((l, idx) => {
              const q = Number(l.qty) || 0;
              const r = Number(l.rate || l.price) || 0;
              const d = Number(l.discount) || 0;
              const g = Number(l.gst) || 0;
              const rateAfterDisc = r * (1 - d / 100);
              const taxable = q * rateAfterDisc;

              return (
                <tr key={idx} className="text-slate-800">
                  <td className="p-1.5 border-r border-slate-300 text-center font-mono">{l.hsnSac || "-"}</td>
                  <td className="p-1.5 border-r border-slate-300 font-semibold">{l.name || "Item Name"}</td>
                  <td className="p-1.5 border-r border-slate-300 text-center font-mono">{q} {l.unit || "Pcs"}</td>
                  <td className="p-1.5 border-r border-slate-300 text-right font-mono">₹{taxable.toFixed(2)}</td>
                  <td className="p-1.5 text-center font-mono">{g}%</td>
                </tr>
              );
            })}

            {lines.length === 0 && (
              <tr>
                <td colSpan={5} className="p-4 text-center text-slate-400 italic">No goods items listed</td>
              </tr>
            )}
          </tbody>
        </table>

        {/* Table 2: Totals Summary Grid */}
        <table className="w-full text-center border-collapse table-fixed border-t border-slate-400">
          <thead>
            <tr className="font-bold text-slate-900 border-b border-slate-400 text-[8.5px]" style={{ backgroundColor: yellowHeaderBg }}>
              <th className="p-1.5 border-r border-slate-400">Tot. Tax'ble Amt</th>
              <th className="p-1.5 border-r border-slate-400">CGST Amt</th>
              <th className="p-1.5 border-r border-slate-400">SGST Amt</th>
              <th className="p-1.5 border-r border-slate-400">IGST Amt</th>
              <th className="p-1.5 border-r border-slate-400">Cess Amt</th>
              <th className="p-1.5 border-r border-slate-400">Cess Non.Advol Amt</th>
              <th className="p-1.5 border-r border-slate-400">Other Amt</th>
              <th className="p-1.5">Tot. Inv. Amt</th>
            </tr>
          </thead>
          <tbody>
            <tr className="font-bold font-mono text-[9px]">
              <td className="p-1.5 border-r border-slate-300">₹{totalTaxable.toFixed(2)}</td>
              <td className="p-1.5 border-r border-slate-300">{totalCgst > 0 ? `₹${totalCgst.toFixed(2)}` : "-"}</td>
              <td className="p-1.5 border-r border-slate-300">{totalSgst > 0 ? `₹${totalSgst.toFixed(2)}` : "-"}</td>
              <td className="p-1.5 border-r border-slate-300">{totalIgst > 0 ? `₹${totalIgst.toFixed(2)}` : "-"}</td>
              <td className="p-1.5 border-r border-slate-300">{totalCess > 0 ? `₹${totalCess.toFixed(2)}` : "-"}</td>
              <td className="p-1.5 border-r border-slate-300">-</td>
              <td className="p-1.5 border-r border-slate-300">-</td>
              <td className="p-1.5 font-black text-slate-900">₹{totalInvAmt.toFixed(2)}</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* 4. Transportation Details */}
      <div className="border border-slate-400 rounded-sm overflow-hidden">
        <div className="py-1 px-2 font-bold text-slate-900 border-b border-slate-400" style={{ backgroundColor: yellowHeaderBg }}>
          4. Transportation Details
        </div>
        <div className="grid grid-cols-2 p-1.5 gap-4">
          <p><span className="text-slate-600">Transport ID & Name:</span> <span className="font-semibold">{transportDetails.transporterId || transportDetails.transporterName ? `${transportDetails.transporterId || ''} - ${transportDetails.transporterName || ''}` : "-"}</span></p>
          <p><span className="text-slate-600">Transport Doc. No. & Date:</span> <span className="font-semibold">{transportDetails.lrNumber ? `${transportDetails.lrNumber} / ${transportDetails.lrDate || meta?.date}` : "-"}</span></p>
        </div>
      </div>

      {/* 5. Vehicle Details */}
      <div className="border border-slate-400 rounded-sm overflow-hidden">
        <div className="py-1 px-2 font-bold text-slate-900 border-b border-slate-400" style={{ backgroundColor: yellowHeaderBg }}>
          5. Vehicle Details
        </div>
        <table className="w-full text-center border-collapse table-fixed">
          <thead>
            <tr className="font-bold text-slate-900 border-b border-slate-400" style={{ backgroundColor: yellowHeaderBg }}>
              <th className="p-1.5 border-r border-slate-400 w-[10%]">Mode</th>
              <th className="p-1.5 border-r border-slate-400 w-[24%]">Vehicle / Transport Doc. No. & Date</th>
              <th className="p-1.5 border-r border-slate-400 w-[12%]">From</th>
              <th className="p-1.5 border-r border-slate-400 w-[14%]">Entered Date</th>
              <th className="p-1.5 border-r border-slate-400 w-[16%]">Entered By</th>
              <th className="p-1.5 border-r border-slate-400 w-[12%]">CEWB No. (If any)</th>
              <th className="p-1.5 w-[12%]">Multi Veh. Info (if any)</th>
            </tr>
          </thead>
          <tbody>
            <tr className="font-mono text-slate-800">
              <td className="p-1.5 border-r border-slate-300">{transportDetails.modeOfTransport || "Road"}</td>
              <td className="p-1.5 border-r border-slate-300 font-bold">{transportDetails.vehicleNumber || transportDetails.vehicleNo || "-"}</td>
              <td className="p-1.5 border-r border-slate-300">{shippingDetails.placeOfDispatch || sellerState || "-"}</td>
              <td className="p-1.5 border-r border-slate-300">{meta?.date || new Date().toLocaleDateString('en-IN')}</td>
              <td className="p-1.5 border-r border-slate-300">{sellerGstin || sellerName}</td>
              <td className="p-1.5 border-r border-slate-300">-</td>
              <td className="p-1.5">-</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Yellow Banner footer block */}
      <div className="h-6 w-full rounded-sm" style={{ backgroundColor: yellowHeaderBg }}></div>

      {/* Footer representation text */}
      <p className="text-[8px] text-slate-500 pt-1">
        This is for representation purpose only. If you would like to create E-way Bill, then download the Vyapar Windows version to create unlimited E-way bills.
      </p>
    </div>
  );
}
